### PR TITLE
Split invalid gallery paragraphs correctly. 

### LINKED ISSUE #12: Exception in convertGalleriesToImages
When running json-wikipedia on [this xml file](https://gist.github.com/keynmol/c52fc127f28fb2cbaf1c) this exception occurs:

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at de.tudarmstadt.ukp.wikipedia.parser.mediawiki.ModularParser.convertGalleriesToImages(ModularParser.java:1085)
	at de.tudarmstadt.ukp.wikipedia.parser.mediawiki.ModularParser.parse(ModularParser.java:398)
	at it.cnr.isti.hpc.wikipedia.parser.ArticleParser.parse(ArticleParser.java:85)
	at it.cnr.isti.hpc.wikipedia.reader.WikipediaArticleReader$JsonConverter.process(WikipediaArticleReader.java:175)
	at info.bliki.wiki.dump.WikiXMLParser.endElement(WikiXMLParser.java:185)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at info.bliki.wiki.dump.WikiXMLParser.parse(WikiXMLParser.java:218)
	at it.cnr.isti.hpc.wikipedia.reader.WikipediaArticleReader.start(WikipediaArticleReader.java:136)
	at it.cnr.isti.hpc.wikipedia.cli.MediawikiToJsonCLI.main(MediawikiToJsonCLI.java:137)
```

To reproduce:

```
java -cp target/json-wikipedia-1.1.0-jar-with-dependencies.jar it.cnr.isti.hpc.wikipedia.cli.MediawikiToJsonCLI -input ford_madox_brown.xml -output bla.jsonl -lang en -action export
```

### PR DESCRIPTION
**Pull request by keynmol**
This resolves #12

### CODE REVIEW

**Comment by Lugrin** [comment]
Does it ever happen that the image paragraph has several `|` characters? Maybe worth adding a test.

File: src/main/java/de/tudarmstadt/ukp/wikipedia/parser/mediawiki/ModularParser.java [hunk 1]
```diff
@@ -1074,7 +1074,8 @@ private void convertGalleriesToImages(SpanManager sm, List<Span> tagSpans)
                     for (String imageParagraph : tokenize(sm, startSpan.getEnd(), endSpan
                         .getStart(), lineSeparator))
                     {
-                        String[] splitImageParagraph = imageParagraph.split("\\|");
+						String[] splitImageParagraph = imageParagraph.split("\\|", -1);
+
```
Comment (Lugrin) [inline src/main/java/de/tudarmstadt/ukp/wikipedia/parser/mediawiki/ModularParser.java]: This line has tabs, but the other ones have spaces.
https://www.dropbox.com/s/s2eve5pcrtmdkn2/Screenshot%202015-08-26%2010.13.14.png?dl=0

Comment (keynmol) [inline src/main/java/de/tudarmstadt/ukp/wikipedia/parser/mediawiki/ModularParser.java]: That's because original code had tabs, but indenting with tabs is a bad practice.

I also didn't want to make the diff unreadable, so in a separate PR I'll do some reformatting.
