### PR TITLE
Handle empty <text ...> tag correctly

### LINKED ISSUE #14: Incorrect handling of empty text
Draft pages can contain empty text tags, like [this page](https://gist.github.com/keynmol/c633bc075e26b7f2dfd4)

```
java.lang.NullPointerException
	at it.cnr.isti.hpc.wikipedia.parser.ArticleParser.removeTemplates(ArticleParser.java:134)
	at it.cnr.isti.hpc.wikipedia.parser.ArticleParser.parse(ArticleParser.java:79)
	at it.cnr.isti.hpc.wikipedia.reader.WikipediaArticleReader$JsonConverter.process(WikipediaArticleReader.java:175)
	at info.bliki.wiki.dump.WikiXMLParser.endElement(WikiXMLParser.java:185)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at info.bliki.wiki.dump.WikiXMLParser.parse(WikiXMLParser.java:218)
	at it.cnr.isti.hpc.wikipedia.reader.WikipediaArticleReader.start(WikipediaArticleReader.java:136)
	at it.cnr.isti.hpc.wikipedia.cli.MediawikiToJsonCLI.main(MediawikiToJsonCLI.java:137)
```

This should be a warning, because it's a legitimate situation where we can't do anything.

### PR DESCRIPTION
**Pull request by keynmol**
Resolves #14

Outputs a warning on an empty page, rather than a meaningless exception.

Also disables travis emails, because screw them.

### CODE REVIEW

File: src/main/java/it/cnr/isti/hpc/wikipedia/parser/ArticleParser.java [hunk 1]
```diff
@@ -76,12 +76,16 @@ public ArticleParser() {
...
-        //String cleanedMediawiki=mediawiki;
-		ParsedPage page = parser.parse(cleanedMediawiki);
-        setRedirect(article, cleanedMediawiki);
-
-		parse(article, page);
+        if (mediawiki == null) {
+            logger.warn("Text is null for article {}", article.getTitle());
+        } else {
+            String cleanedMediawiki = removeTemplates(mediawiki);
+            //String cleanedMediawiki=mediawiki;
```
Comment (dav009) [inline src/main/java/it/cnr/isti/hpc/wikipedia/parser/ArticleParser.java]: comment
