### PR TITLE
Write namespaces tag in parallel mode

### LINKED ISSUE #25: Incorrect namespaces handling in parallel mode
Related to #18, apparently bliki reads the `<namespaces>` tag to figure out prefixes and we don't write this tag when we split the XML dump.

Hence the same problem as in #18 arises.

### PR DESCRIPTION
**Pull request by keynmol**
Closes #25.

Just write the list of namespaces to every split of xml dump, otherwise bliki doesn't pick up namespace (why it wouldn't look at the <ns> tag I have no idea)

Why is it important? without properly recognising wikipedia namespace, pages [like this](https://en.wikipedia.org/wiki/Wikipedia:0.8/First_half) are recognised as articles and it later on skews context vectors for most of the dbpedia ids.

### CODE REVIEW

**Comment by dav009** [comment]
looks good. 
Tho in the ideal case we would parse the first lines of the wiki and extract this automatically I guess

File: src/main/scala/it/cnr/isti/hpc/wikipedia/parallel/ParallelJsonpediaParser.scala [hunk 1]
```diff
@@ -17,12 +17,15 @@ object ParallelJsonpediaParser{
...
+
     println("Adding headers, footers to files...")
     files.par.map{ f =>
       println("processing.." + f.getName())
       val content = scala.io.Source.fromFile(f,  "utf-8").getLines().toList
       val fw = new FileWriter(f, false)
       fw.write(header +"\n")
+      fw.write(namespaces+"\n")
```
Comment (dav009) [inline src/main/scala/it/cnr/isti/hpc/wikipedia/parallel/ParallelJsonpediaParser.scala]: space

**Comment by dav009** [comment]
go for it speedracer ;)
