### PR TITLE
Fixing colon bug - Extracting weird sf and topic Ids 

### LINKED ISSUE #7: Annotations containing `:`
https://en.wikipedia.org/wiki/Hayami
contains some links in lists, those dbpedia Ids contains: `:` . i.e : 
 - `''[[R:Racing Evolution]]''`
 - `''[[H2O: Footprints in the Sand]]''`

Those links are being skipped. 
Probably a problem with jwpl.

### PR DESCRIPTION
**Pull request by dav009**
Fixes #7 

what was going on?

- annotations come in the following format: `[[` `NE` : `TopicId` | `SF` `]]`. `NE` is optional, so for most annotations we dont see it.

Here some examples:
 - `[[ es:manzana|Apple ]]`
 - `[[:es:manzana|Apple]]` <- some people love `:` (this is a language NE, `es` stands for spanish)
 - `[[::::es:manzana|Apple]]` <- some people really love `:` 
 - `[[cite:ABC]]`  <- this is a different NE, used for citations in the english wiki, yes NE are language dependent)

- `[[h20:ABC]]` <- a topic whose name is `h20:ABC` no namespace.
- `[[Apple]]` <- Annotation without NE
- `[[:Apple]]` <- Same as the previous case but some people really love `:`
- ... more acases where the SF includes `:` but for this bug they dont matter

----------------
The problem was parsing the NE was done in a very simple manner. So the NE would be considered to be anything between the beginning of the string until the first `:`. So this PR:

- Parses the NE to handle the cases explained above. This is done via a regular expression.
- If a NE is not in our list of NE i.e: `h20` then it will be considered to be part of the topic's Id
- Annotations with language NE were already handled by JWPL putting them in a different category than our `links` field. But because of the bad parsing, they did not get handled properly and thus made it to our `links` field. With this fix, those annotations with language should follow the intended processing.
- Also for annotations such as:`[:::ABC]` or `[[NE::ABC]]` it makes sure that the `anchor` text for that annotation comes without the `NE`  and the `:`
- Added a bunch of tests for `ModularParser` (jwpl)
- Added a bunch of tests on the jsonpedia side

### CODE REVIEW

File: src/test/java/de/tudarmstadt/ukp/wikipedia/parser/ModularParserTest.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+		Pair<String, String> withNE2 = ModularParser.extractNETopic(":::fr:SansNE");
+		assert(withNE2.getFirst().equals("fr"));
+		assert(withNE2.getSecond().equals("SansNE"));
+
+		Pair<String, String> withNE3 = ModularParser.extractNETopic(":::fr:h20:japanese");
+		assert(withNE3.getFirst().equals("fr"));
+		assert(withNE3.getSecond().equals("h20:japanese"));
+
+		Pair<String, String> withNE4 = ModularParser.extractNETopic("h20:japanese");
+		assert(withNE4.getFirst().equals("h20"));
```
Comment (keynmol) [inline src/test/java/de/tudarmstadt/ukp/wikipedia/parser/ModularParserTest.java]: Is that really how it's supposed to be broken down? I thought it would be `("", "h20:japanese")`

Comment (keynmol) [inline src/test/java/de/tudarmstadt/ukp/wikipedia/parser/ModularParserTest.java]: Ah, never mind, I see below.

File: src/test/java/de/tudarmstadt/ukp/wikipedia/parser/ParserTest.java [hunk 2]
```diff
@@ -161,6 +164,39 @@ public void testExtractingLinksWithColons(){
...
+				"* Les petites  marmites, comédie en trois actes, Théâtre du Gymnase\n" +
+				"[[cite:Gundam]] * Voilà Monsieur !, comédie en un acte, Théâtre du Gymnase";
+
+		MediaWikiParserFactory pf = new MediaWikiParserFactory(WikiConstants.Language.english);
+		MediaWikiParser parser = pf.createParser();
+
+		ParsedPage pp = parser.parse(text);
+
+		List<String> uris = getUrisInParagraphs(pp);
+		assertFalse(uris.contains("André_Delavigne"));
```
Comment (keynmol) [inline src/test/java/de/tudarmstadt/ukp/wikipedia/parser/ParserTest.java]: So does it mean that our annotations will contain links to other languages? That's inconsistent data, don't you think?

Comment (dav009) [inline src/test/java/de/tudarmstadt/ukp/wikipedia/parser/ParserTest.java]: Nope, It won't contain them.

If an annotation comes as `[[LANGUAGE:XX]]` or `[[::::LANGUAGE:XX]]`  then it wont end up in the field that we use for the paragraphLinks.

Comment (keynmol) [inline src/test/java/de/tudarmstadt/ukp/wikipedia/parser/ParserTest.java]: okaaaaaaay then

**Comment by keynmol** [comment]
Good.

File: src/main/java/de/tudarmstadt/ukp/wikipedia/parser/mediawiki/ModularParser.java [hunk 3]
```diff
@@ -1625,7 +1669,7 @@ private void parseImagesAndInternalLinks(SpanManager sm,
 				}
 				else
 				{
-					if (allNamespaces.contains(namespace.toLowerCase()))
+					if (Namespaces.allNamespaces.contains(namespace.toLowerCase()))
```
Comment (dav009) [inline src/main/java/de/tudarmstadt/ukp/wikipedia/parser/mediawiki/ModularParser.java]: `isNamespace` should be used here

**Comment by dav009** [comment]
tested this on some our small wikis.
Added other missing NEs

Im going to generate a jsonpedia from the whole wiki.

**Comment by dav009** [comment]
Generated a new jsonpedia + stats. Checked, it looks sane, except for another bunch of NE which I just added to the set.
